markdown: rdiscount
pygments: true

title: Ants, Genomes & Evolution Lab @ Queen Mary University London

url: http://arkokoley.github.io/bootstrapy

permalink: "/news/:year-:month-:day-:title/"
paginate: 4
paginate_file: news/index.html

author:
    name: Yannick Wurm
    email: y.wurm@qmul.ac.uk
    github: yannickwurm
    twitter: yannick__
    gravatar: 

comments:
    provider: disqus
    disqus:
        short_name: 
        
analytics:
    provider: google 
    google: 
        tracking_id: ''
        domain: ''
