auto: true
markdown: rdiscount
pygments: true

title: Yannick Wurm

url: http://arkokoley.github.io/bootstrapy

permalink: /:year/:month/:day/:title/

author:
    name: Yannick Wurm
    email: y.wurm@qmul.ac.uk
    github: 
    twitter: yannick__
    gravatar: 

comments:
    provider: disqus
    disqus:
        short_name: 
        
analytics:
    provider: google 
    google: 
        tracking_id: ''
        domain: ''
