markdown: rdiscount
pygments: true

title: Ants, Genomes & Evolution @ Queen Mary University London

url: /./

permalink: "/news/:year-:month-:day-:title/"

author:
    name: Yannick Wurm
    email: y.wurm@qmul.ac.uk
    github: yannickwurm
    twitter: yannick__
    gravatar: 

comments:
    provider: disqus
    disqus:
        short_name: 
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-471841-2'
        domain: 'yannick.poulet.org'
